In [27]:
import pandas as pd
df = pd.read_parquet('/Users/lithrur/Desktop/Coding projects/hackathon_2025_ai/dataset/DECENTRATHON_3.0.parquet')
df.to_csv('/Users/lithrur/Desktop/Coding projects/hackathon_2025_ai/dataset/dataset.csv', index=False)

print("Loaded rows:", len(df))

print(df.info())

Loaded rows: 11536850
<class 'pandas.core.frame.DataFrame'>
Index: 11536850 entries, 0 to 11536849
Data columns (total 16 columns):
 #   Column                  Dtype
---  ------                  -----
 0   transaction_id          string
 1   transaction_timestamp   datetime64[us]
 2   card_id                 Int64
 3   expiry_date             string
 4   issuer_bank_name        object
 5   merchant_id             Int64
 6   merchant_mcc            Int64
 7   mcc_category            string
 8   merchant_city           string
 9   transaction_type        string
 10  transaction_amount_kzt  Float64
 11  original_amount         Float64
 12  transaction_currency    string
 13  acquirer_country_iso    string
 14  pos_entry_mode          string
 15  wallet_type             string
dtypes: Float64(2), Int64(3), datetime64[us](1), object(1), string(9)
memory usage: 1.5+ GB
None

In [28]:
df

,transaction_id,transaction_timestamp,card_id,expiry_date,issuer_bank_name,merchant_id,merchant_mcc,mcc_category,merchant_city,transaction_type,transaction_amount_kzt,original_amount,transaction_currency,acquirer_country_iso,pos_entry_mode,wallet_type
0,ffb21bbd-fef1-4983-9774-3b01c8fc2537,2023-08-12 23:14:19.043176,10000,09/26,My Favorite Bank,50359,5499,Grocery & Food Markets,Shymkent,POS,1237.66,<NA>,KZT,KAZ,Contactless,Apple Pay
1,acd754f9-bd4c-416d-babc-926050ffe8c4,2023-08-12 17:07:08.641030,10000,09/26,My Favorite Bank,50359,5499,Grocery & Food Markets,Shymkent,POS,2328.03,<NA>,KZT,KAZ,QR_Code,Bank's QR
2,b023697b-eb35-40e6-af75-3586c60acbfb,2023-08-12 08:45:32.946846,10000,09/26,My Favorite Bank,50214,4814,Utilities & Bill Payments,Almaty,BILL_PAYMENT,53871.78,<NA>,KZT,KAZ,<NA>,<NA>
3,d59d8537-1e48-41b5-91e1-dc7cf9d0c776,2023-08-12 10:20:20.242510,10000,09/26,My Favorite Bank,50279,8011,Pharmacies & Health,Shymkent,POS,22501.56,<NA>,KZT,KAZ,Contactless,Apple Pay
4,85d2eef6-3b09-47a6-987f-f45ab491282f,2023-08-12 00:42:00.556252,10000,09/26,My Favorite Bank,50332,5499,Grocery & Food Markets,Almaty,POS,1224.04,<NA>,KZT,KAZ,QR_Code,Bank's QR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11536845,79beb18b-88ea-426f-a03b-38faade056d1,2024-12-31 17:49:20.692872,11999,01/28,My Favorite Bank,<NA>,<NA>,Unknown,<NA>,ATM_WITHDRAWAL,57000.0,<NA>,KZT,KAZ,Contactless,<NA>
11536846,0252b672-9033-4621-9b73-08395eae3925,2024-12-31 12:57:38.022726,11999,01/28,My Favorite Bank,50214,5311,General Retail & Department,Almaty,ECOM,18661.51,<NA>,KZT,KAZ,ECOM,Google Pay
11536847,91ec9300-e7af-4423-b1db-9b0be4077c70,2024-12-31 14:32:13.832646,11999,01/28,My Favorite Bank,50306,4814,Utilities & Bill Payments,Almaty,POS,6161.15,<NA>,KZT,KAZ,Chip,<NA>
11536848,8350ae75-4637-48cc-bc55-0243c4a21fb6,2024-12-31 08:54:37.277956,11999,01/28,My Favorite Bank,<NA>,<NA>,Unknown,<NA>,ATM_WITHDRAWAL,29000.0,<NA>,KZT,KAZ,Chip,<NA>
11536849,6dec4068-46c2-4058-85d0-b4244aa84e69,2024-12-31 16:13:48.675766,11999,01/28,My Favorite Bank,<NA>,<NA>,Unknown,<NA>,ATM_WITHDRAWAL,15000.0,<NA>,KZT,KAZ,Contactless,<NA>

In [29]:
df.drop(columns=['transaction_id', 'expiry_date', 'issuer_bank_name', 'merchant_id', 'merchant_mcc', 'original_amount', 'acquirer_country_iso'], inplace=True)
df

,transaction_timestamp,card_id,mcc_category,merchant_city,transaction_type,transaction_amount_kzt,transaction_currency,pos_entry_mode,wallet_type
0,2023-08-12 23:14:19.043176,10000,Grocery & Food Markets,Shymkent,POS,1237.66,KZT,Contactless,Apple Pay
1,2023-08-12 17:07:08.641030,10000,Grocery & Food Markets,Shymkent,POS,2328.03,KZT,QR_Code,Bank's QR
2,2023-08-12 08:45:32.946846,10000,Utilities & Bill Payments,Almaty,BILL_PAYMENT,53871.78,KZT,<NA>,<NA>
3,2023-08-12 10:20:20.242510,10000,Pharmacies & Health,Shymkent,POS,22501.56,KZT,Contactless,Apple Pay
4,2023-08-12 00:42:00.556252,10000,Grocery & Food Markets,Almaty,POS,1224.04,KZT,QR_Code,Bank's QR
...,...,...,...,...,...,...,...,...,...
11536845,2024-12-31 17:49:20.692872,11999,Unknown,<NA>,ATM_WITHDRAWAL,57000.0,KZT,Contactless,<NA>
11536846,2024-12-31 12:57:38.022726,11999,General Retail & Department,Almaty,ECOM,18661.51,KZT,ECOM,Google Pay
11536847,2024-12-31 14:32:13.832646,11999,Utilities & Bill Payments,Almaty,POS,6161.15,KZT,Chip,<NA>
11536848,2024-12-31 08:54:37.277956,11999,Unknown,<NA>,ATM_WITHDRAWAL,29000.0,KZT,Chip,<NA>
11536849,2024-12-31 16:13:48.675766,11999,Unknown,<NA>,ATM_WITHDRAWAL,15000.0,KZT,Contactless,<NA>

In [30]:
import numpy as np

hours = df['transaction_timestamp'].dt.hour.values  
#    → this is a NumPy array of length 11 000 000, very fast

# 2) build a 24-element lookup table
hour_labels = np.array(['Night'] * 24, dtype=object)
hour_labels[ 5:12] = 'Morning'    # 05:00–11:59
hour_labels[12:17] = 'Afternoon'  # 12:00–16:59
hour_labels[17:21] = 'Evening'    # 17:00–20:59
# hours 21–23, 0–4 remain 'Night'

# 3) index into it
df['time_of_day'] = hour_labels[hours]

df.drop(columns=['transaction_timestamp'], inplace=True)

In [31]:
cities = df['merchant_city']

# 2. Get the unique city names as a NumPy array
cities.dropna(inplace=True)  # Remove any NaN values
unique_cities = cities.unique()

# 3. (Optional) Sort them and turn into a list for easy reading
unique_cities_sorted = sorted(unique_cities.tolist())

print(unique_cities_sorted) 

print(df['merchant_city'].value_counts())

['Aktobe', 'Almaty', 'Astana', 'Karaganda', 'Other', 'Shymkent']
merchant_city
Almaty       2948927
Astana       2396110
Other        1381156
Shymkent     1345571
Karaganda     621137
Aktobe        374652
Name: count, dtype: Int64

In [32]:
# 1. Define your mapping
city_to_code = {
    "Almaty":     1,
    "Astana":     2,
    "Other":      3,
    "Shymkent":   4,
    "Karaganda":  5,
    "Aktobe":     6
}

# 2. Create a new coded column (or overwrite the old one)
df["merchant_city_code"] = df["merchant_city"].map(city_to_code)

# 3. (Optional) If you really want to replace the text column:
# df["merchant_city"] = df["merchant_city"].map(city_to_code)

# 4. Quick check
print(df[["merchant_city", "merchant_city_code"]])

         merchant_city  merchant_city_code
0             Shymkent                 4.0
1             Shymkent                 4.0
2               Almaty                 1.0
3             Shymkent                 4.0
4               Almaty                 1.0
...                ...                 ...
11536845          <NA>                 NaN
11536846        Almaty                 1.0
11536847        Almaty                 1.0
11536848          <NA>                 NaN
11536849          <NA>                 NaN

[11536850 rows x 2 columns]

In [33]:
cities = df['mcc_category']

# 2. Get the unique city names as a NumPy array
cities.dropna(inplace=True)  # Remove any NaN values
unique_cities = cities.unique()

# 3. (Optional) Sort them and turn into a list for easy reading
unique_cities_sorted = sorted(unique_cities.tolist())

print(unique_cities_sorted) 

print(df['mcc_category'].value_counts())

['Clothing & Apparel', 'Dining & Restaurants', 'Electronics & Software', 'Fuel & Service Stations', 'General Retail & Department', 'Grocery & Food Markets', 'Hobby, Books, Sporting Goods', 'Home Furnishings & Supplies', 'Pharmacies & Health', 'Services (Other)', 'Travel & Transportation', 'Unknown', 'Utilities & Bill Payments']
mcc_category
Unknown                         2470036
Grocery & Food Markets          1986041
Utilities & Bill Payments       1926020
Dining & Restaurants            1088094
Services (Other)                 826466
General Retail & Department      672537
Clothing & Apparel               612452
Fuel & Service Stations          456068
Travel & Transportation          384230
Electronics & Software           333547
Pharmacies & Health              309931
Home Furnishings & Supplies      244809
Hobby, Books, Sporting Goods     226619
Name: count, dtype: Int64

In [34]:
# 1. Define your ordered list of categories
categories = [
    "Clothing & Apparel",
    "Dining & Restaurants",
    "Electronics & Software",
    "Fuel & Service Stations",
    "General Retail & Department",
    "Grocery & Food Markets",
    "Hobby, Books, Sporting Goods",
    "Home Furnishings & Supplies",
    "Pharmacies & Health",
    "Services (Other)",
    "Travel & Transportation",
    "Unknown",
    "Utilities & Bill Payments"
]

# 2. Build the mapping dict
cat_to_code = {cat: idx+1 for idx, cat in enumerate(categories)}

# 3. Replace the column in-place
df['mcc_category'] = df['mcc_category'].map(cat_to_code)

# 4. Verify
print(df['mcc_category'].unique())

[ 6 13  9  5 12 10  3  2  1 11  7  4  8]

In [35]:
df.drop(columns=['merchant_city'], inplace=True)
df

,card_id,mcc_category,transaction_type,transaction_amount_kzt,transaction_currency,pos_entry_mode,wallet_type,time_of_day,merchant_city_code
0,10000,6,POS,1237.66,KZT,Contactless,Apple Pay,Night,4.0
1,10000,6,POS,2328.03,KZT,QR_Code,Bank's QR,Evening,4.0
2,10000,13,BILL_PAYMENT,53871.78,KZT,<NA>,<NA>,Morning,1.0
3,10000,9,POS,22501.56,KZT,Contactless,Apple Pay,Morning,4.0
4,10000,6,POS,1224.04,KZT,QR_Code,Bank's QR,Night,1.0
...,...,...,...,...,...,...,...,...,...
11536845,11999,12,ATM_WITHDRAWAL,57000.0,KZT,Contactless,<NA>,Evening,NaN
11536846,11999,5,ECOM,18661.51,KZT,ECOM,Google Pay,Afternoon,1.0
11536847,11999,13,POS,6161.15,KZT,Chip,<NA>,Afternoon,1.0
11536848,11999,12,ATM_WITHDRAWAL,29000.0,KZT,Chip,<NA>,Morning,NaN
11536849,11999,12,ATM_WITHDRAWAL,15000.0,KZT,Contactless,<NA>,Afternoon,NaN

In [36]:
print("Loaded rows:", len(df))

print(df.info())

Loaded rows: 11536850
<class 'pandas.core.frame.DataFrame'>
Index: 11536850 entries, 0 to 11536849
Data columns (total 9 columns):
 #   Column                  Dtype
---  ------                  -----
 0   card_id                 Int64
 1   mcc_category            int64
 2   transaction_type        string
 3   transaction_amount_kzt  Float64
 4   transaction_currency    string
 5   pos_entry_mode          string
 6   wallet_type             string
 7   time_of_day             object
 8   merchant_city_code      float64
dtypes: Float64(1), Int64(1), float64(1), int64(1), object(1), string(4)
memory usage: 902.2+ MB
None

In [37]:
df['wallet_type'] = (
    df['wallet_type']
    .fillna('card')        # NaNs → 'card'
    .replace('', 'card')   # empty strings → 'card'
)
df

,card_id,mcc_category,transaction_type,transaction_amount_kzt,transaction_currency,pos_entry_mode,wallet_type,time_of_day,merchant_city_code
0,10000,6,POS,1237.66,KZT,Contactless,Apple Pay,Night,4.0
1,10000,6,POS,2328.03,KZT,QR_Code,Bank's QR,Evening,4.0
2,10000,13,BILL_PAYMENT,53871.78,KZT,<NA>,card,Morning,1.0
3,10000,9,POS,22501.56,KZT,Contactless,Apple Pay,Morning,4.0
4,10000,6,POS,1224.04,KZT,QR_Code,Bank's QR,Night,1.0
...,...,...,...,...,...,...,...,...,...
11536845,11999,12,ATM_WITHDRAWAL,57000.0,KZT,Contactless,card,Evening,NaN
11536846,11999,5,ECOM,18661.51,KZT,ECOM,Google Pay,Afternoon,1.0
11536847,11999,13,POS,6161.15,KZT,Chip,card,Afternoon,1.0
11536848,11999,12,ATM_WITHDRAWAL,29000.0,KZT,Chip,card,Morning,NaN
11536849,11999,12,ATM_WITHDRAWAL,15000.0,KZT,Contactless,card,Afternoon,NaN

In [38]:
import numpy as np

# Option A: overwrite the column with 0/1
df['transaction_currency'] = np.where(
    df['transaction_currency'] == 'KZT', 
    0, 
    1
)

# Option B: keep the original and make a new code column
df['transaction_currency_code'] = np.where(
    df['transaction_currency'] == 'KZT', 
    0, 
    1
)

In [39]:
df['transaction_type'].unique()

<StringArray>
['POS', 'BILL_PAYMENT', 'ECOM', 'ATM_WITHDRAWAL', 'P2P_OUT', 'P2P_IN',
 'SALARY']
Length: 7, dtype: string

In [40]:
# 1. Define the ordered list of your transaction types
types = [
    'POS',
    'BILL_PAYMENT',
    'ECOM',
    'ATM_WITHDRAWAL',
    'P2P_OUT',
    'P2P_IN',
    'SALARY'
]

# 2. Build a mapping dict (1-based codes)
type_to_code = {t: i+1 for i, t in enumerate(types)}

# 3. Replace the column in-place
df['transaction_type'] = df['transaction_type'].map(type_to_code)

# 4. Verify you now have codes 1–7 only
print(df['transaction_type'].unique())
print(df['transaction_type'].value_counts())

[1 2 3 4 5 6 7]
transaction_type
1    5793598
3    1905761
2    1367455
4    1184079
5     648058
6     617386
7      20513
Name: count, dtype: int64

In [41]:
df.head()

,card_id,mcc_category,transaction_type,transaction_amount_kzt,transaction_currency,pos_entry_mode,wallet_type,time_of_day,merchant_city_code,transaction_currency_code
0,10000,6,1,1237.66,0,Contactless,Apple Pay,Night,4.0,1
1,10000,6,1,2328.03,0,QR_Code,Bank's QR,Evening,4.0,1
2,10000,13,2,53871.78,0,<NA>,card,Morning,1.0,1
3,10000,9,1,22501.56,0,Contactless,Apple Pay,Morning,4.0,1
4,10000,6,1,1224.04,0,QR_Code,Bank's QR,Night,1.0,1

In [42]:
pd.crosstab(
    df['pos_entry_mode'].fillna('Unknown'),
    df['wallet_type'].fillna('Unknown'),
    dropna=False
)

wallet_type     Apple Pay  Bank's QR  Google Pay  Samsung Pay     card
pos_entry_mode
Chip                    0          0           0            0  1219989
Contactless        558159          0      556722       559726   591015
ECOM               635309          0      635886       634566        0
QR_Code                 0    3282988           0            0        0
Swipe                   0          0           0            0   209078
Unknown                 0          0           0            0  2653412

In [43]:
# 1. Define the mappings
wallet_map = {
    "Apple Pay":       1,
    "Bank's QR":       2,
    "Google Pay":      3,
    "Samsung Pay":     4,
    "card":            5
}

pos_map = {
    "Chip":            1,
    "Contactless":     2,
    "ECOM":            3,
    "QR_Code":         4,
    "Swipe":           5,
    "Unknown":         6
}

# 2. Replace in-place
df['wallet_type']    = df['wallet_type'].map(wallet_map)
df['pos_entry_mode'] = df['pos_entry_mode'].map(pos_map)

# 3. Verify
print(df[['wallet_type','pos_entry_mode']].drop_duplicates().reset_index(drop=True))

    wallet_type  pos_entry_mode
0             1             2.0
1             2             4.0
2             5             NaN
3             4             3.0
4             1             3.0
5             5             2.0
6             5             5.0
7             5             1.0
8             4             2.0
9             3             3.0
10            3             2.0

In [44]:
df

,card_id,mcc_category,transaction_type,transaction_amount_kzt,transaction_currency,pos_entry_mode,wallet_type,time_of_day,merchant_city_code,transaction_currency_code
0,10000,6,1,1237.66,0,2.0,1,Night,4.0,1
1,10000,6,1,2328.03,0,4.0,2,Evening,4.0,1
2,10000,13,2,53871.78,0,NaN,5,Morning,1.0,1
3,10000,9,1,22501.56,0,2.0,1,Morning,4.0,1
4,10000,6,1,1224.04,0,4.0,2,Night,1.0,1
...,...,...,...,...,...,...,...,...,...,...
11536845,11999,12,4,57000.0,0,2.0,5,Evening,NaN,1
11536846,11999,5,3,18661.51,0,3.0,3,Afternoon,1.0,1
11536847,11999,13,1,6161.15,0,1.0,5,Afternoon,1.0,1
11536848,11999,12,4,29000.0,0,1.0,5,Morning,NaN,1
11536849,11999,12,4,15000.0,0,2.0,5,Afternoon,NaN,1

In [45]:
df['time_of_day'].unique()

array(['Night', 'Evening', 'Morning', 'Afternoon'], dtype=object)

In [46]:
# 1. Define the mapping
time_map = {
    "Night":     1,
    "Evening":   2,
    "Morning":   3,
    "Afternoon": 4
}

# 2. Replace in-place
df['time_of_day'] = df['time_of_day'].map(time_map)

# 3. Verify
print(df['time_of_day'].unique())  # should show [1,2,3,4]

[1 2 3 4]

In [47]:
df

,card_id,mcc_category,transaction_type,transaction_amount_kzt,transaction_currency,pos_entry_mode,wallet_type,time_of_day,merchant_city_code,transaction_currency_code
0,10000,6,1,1237.66,0,2.0,1,1,4.0,1
1,10000,6,1,2328.03,0,4.0,2,2,4.0,1
2,10000,13,2,53871.78,0,NaN,5,3,1.0,1
3,10000,9,1,22501.56,0,2.0,1,3,4.0,1
4,10000,6,1,1224.04,0,4.0,2,1,1.0,1
...,...,...,...,...,...,...,...,...,...,...
11536845,11999,12,4,57000.0,0,2.0,5,2,NaN,1
11536846,11999,5,3,18661.51,0,3.0,3,4,1.0,1
11536847,11999,13,1,6161.15,0,1.0,5,4,1.0,1
11536848,11999,12,4,29000.0,0,1.0,5,3,NaN,1
11536849,11999,12,4,15000.0,0,2.0,5,4,NaN,1

In [48]:
num_cols = df.select_dtypes(include=['number']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())
df

,card_id,mcc_category,transaction_type,transaction_amount_kzt,transaction_currency,pos_entry_mode,wallet_type,time_of_day,merchant_city_code,transaction_currency_code
0,10000,6,1,1237.66,0,2.000000,1,1,4.000000,1
1,10000,6,1,2328.03,0,4.000000,2,2,4.000000,1
2,10000,13,2,53871.78,0,2.886929,5,3,1.000000,1
3,10000,9,1,22501.56,0,2.000000,1,3,4.000000,1
4,10000,6,1,1224.04,0,4.000000,2,1,1.000000,1
...,...,...,...,...,...,...,...,...,...,...
11536845,11999,12,4,57000.0,0,2.000000,5,2,2.494664,1
11536846,11999,5,3,18661.51,0,3.000000,3,4,1.000000,1
11536847,11999,13,1,6161.15,0,1.000000,5,4,1.000000,1
11536848,11999,12,4,29000.0,0,1.000000,5,3,2.494664,1
11536849,11999,12,4,15000.0,0,2.000000,5,4,2.494664,1

In [49]:
df.to_csv('/Users/lithrur/Desktop/Coding projects/hackathon_2025_ai/dataset/dataset_cleaned.csv', index=False)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11536850 entries, 0 to 11536849
Data columns (total 10 columns):
 #   Column                     Dtype
---  ------                     -----
 0   card_id                    Int64
 1   mcc_category               int64
 2   transaction_type           int64
 3   transaction_amount_kzt     Float64
 4   transaction_currency       int64
 5   pos_entry_mode             float64
 6   wallet_type                int64
 7   time_of_day                int64
 8   merchant_city_code         float64
 9   transaction_currency_code  int64
dtypes: Float64(1), Int64(1), float64(2), int64(6)
memory usage: 990.2 MB

In [62]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [63]:
import pandas as pd

# 1. Загрузить агрегированные фичи (customer-level)
from customer_segmentation_per_user import aggregate_features

# Укажите свой путь к исходному CSV
df = pd.read_csv('/Users/lithrur/Desktop/Coding projects/hackathon_2025_ai/dataset/dataset_cleaned.csv')
cust_feats = aggregate_features(df)

# 2. Собрать словарь с описаниями
rows = []
for col in cust_feats.columns:
    dtype = str(cust_feats[col].dtype)
    if col.endswith('_sum') or col.endswith('_mean') or col.endswith('_std'):
        base, stat = col.rsplit('_', 1)
        desc = {
            'sum':  'Сумма транзакций/значений',
            'mean': 'Среднее транзакций/значений',
            'std' : 'Стандартное отклонение транзакций/значений'
        }[stat] + f" для поля `{base}` на одного клиента"
        source = "groupby(card_id).agg"
    else:
        # колонки one-hot
        prefix, val = col.split('_', 1)
        desc = f"Число транзакций, где `{prefix}` = «{val}»"
        source = "one-hot encode + groupby(card_id).sum()"
    rows.append({
        "Field": col,
        "Type": dtype,
        "Description": desc,
        "Formula/Source": source
    })

data_dict = pd.DataFrame(rows)


data_dict.to_excel('data_dictionary.xlsx', index=False)

print("Data Dictionary создан:\n", data_dict.head(10))

Data Dictionary создан:
                          Field     Type  \
0   transaction_amount_kzt_sum  float64
1  transaction_amount_kzt_mean  float64
2   transaction_amount_kzt_std  float64
3       merchant_city_code_sum  float64
4      merchant_city_code_mean  float64
5       merchant_city_code_std  float64
6       transaction_type_1_sum    int64
7       transaction_type_2_sum    int64
8       transaction_type_3_sum    int64
9       transaction_type_4_sum    int64

                                         Description        Formula/Source
0  Сумма транзакций/значений для поля `transactio...  groupby(card_id).agg
1  Среднее транзакций/значений для поля `transact...  groupby(card_id).agg
2  Стандартное отклонение транзакций/значений для...  groupby(card_id).agg
3  Сумма транзакций/значений для поля `merchant_c...  groupby(card_id).agg
4  Среднее транзакций/значений для поля `merchant...  groupby(card_id).agg
5  Стандартное отклонение транзакций/значений для...  groupby(card_id).agg
6  Сумма транзакций/значений для поля `transactio...  groupby(card_id).agg
7  Сумма транзакций/значений для поля `transactio...  groupby(card_id).agg
8  Сумма транзакций/значений для поля `transactio...  groupby(card_id).agg
9  Сумма транзакций/значений для поля `transactio...  groupby(card_id).agg

In [64]:
import pandas as pd

# 1. Путь к вашему CSV
csv_path = "/Users/lithrur/Desktop/Coding projects/hackathon_2025_ai/customer_segments.csv"

# 2. Читаем CSV
df = pd.read_csv(csv_path)

# 3. Путь к выходному Parquet (обычно расширение .parquet)
parquet_path = "/Users/lithrur/Desktop/Coding projects/hackathon_2025_ai/customer_segments.parquet"

# 4. Сохраняем в Parquet
df.to_parquet(parquet_path, index=False)